game:
  env_id: "SafetyPointGoal1-v0"
  with_human: False  # One or two humans if True
  use_image_obs: False

VICRL:
  layer1_size: 64  # number of neurons in the first hidden layer
  layer2_size: 64  # number of neurons in the second hidden layer
  lr: 0.00003  # learning rate of policy, value, and cost networks
  n_steps: 2000  # number of steps per episode
  forward_steps: 200000  # number of steps per iteration (iterations = N of Algorithm 1 in ICRL)
  n_iters: 50  # number of iterations (N). n_iters*forward_steps gives the total number of steps
  reward_gamma: 0.99
  reward_gae_lambda: 0.9
  reward_vf_coef: 0.5
  max_grad_norm: 0.5
  batch_size: 128
  epochs: 20  # number of policy, value, and cost networks updates per episode
  clip_range: 0.4
  target_kl: 0.02
  w_constraint_optimization: True
  constraint_net_layer1_size: 40
  constraint_net_layer2_size: 40
  constraint_net_regularizer_coeff: 0.6
  constraint_net_cn_lr: 0.005
  constraint_net_anneal_clr_by_factor: 0.9
  constraint_net_target_kl_old_new: 10
  constraint_net_target_kl_new_old: 2.5
  cost_gamma: 0.99
  cost_gae_lambda: 0.9
  cost_vf_coef: 0.5
  lambda_initial_value: 0.1
  lambda_lr: 0.05
  alpha_cost: 0.0
  backward_iterations: 5
  backward_n_rollouts: 50
  constraint_net_batch_size: None
  constraint_net_importance_sampling: False
  constraint_net_di_prior: [0.9, 0.1]
  constraint_net_mode: 'sample'

  # Demonstrations
  expert_dataset_path: '~/demonstrations/SafetyPointGoal1-v0/human_alone_exp_human_data_simple_w_action_smooth=0.5/tmp/demonstrations'
  load_demos_in_memory: True
  smooth_actions: False
  smooth_factor: 0.99

Experiment:

  # Normalization
  normalize_features: True
  normalize_rewards: False

  # Logging
  test_every_episodes: 10  # episodes interval between tests
  log_interval: 10  # print avg reward in the interval

  # Games/Steps
  max_timesteps_per_game: 1000  # max timesteps per episode in train mode. For "Circle" tasks, use 500.
  test_max_timesteps_per_game: 1000  # max steps per episode in test mode. For "Circle" tasks, use 500.
  test_max_games: 40  # print avg test reward in the interval

  # Saving
  save_model: True
  save_data_for_plots: False

  # Testing
  test_model: False  # if True, no training
  load_checkpoint: False
  checkpoint_path: "~/train_results/tmp/chkpts"
  checkpoint_prefix: "last"  # Options: "best_reward", "lowest_constr", "last"

  render: False
  debug_: False
  test_window_size_moving_avg: 10
  seed: None  # None or int
  test_seed: 2024  # None or int
  device: "cpu"  # "cuda" or "cpu"
  torch_threads: 1


# Different configs found in: https://github.com/Guiliang/ICRL-benchmarks-public/blob/main/config
#  1) lr=0.00003, n_steps=2000, forward_steps=200000, n_iters=30, reward_gae_lambda=0.95, batch_size=64, epochs=10, clip_range=0.2, target_kl=0.01, constraint_net_layer1_size=20, constraint_net_layer2_size=None, constraint_net_regularizer_coeff=0.5, constraint_net_cn_lr=0.005, constraint_net_anneal_clr_by_factor=0.9, cost_gae_lambda=0.95, lambda_initial_value=1.0, lambda_lr=0.1, backward_iterations=10, backward_n_rollouts=10, constraint_net_batch_size=None, constraint_net_di_prior=[0.9, 0.1]
#  2) same as (1) but with constraint_net_di_prior=[9, 1]
#  3) lr=0.00003, n_steps=2000, forward_steps=200000, n_iters=100, reward_gae_lambda=0.9, batch_size=128, epochs=20, clip_range=0.4, target_kl=0.02, constraint_net_layer1_size=64, constraint_net_layer2_size=64, constraint_net_regularizer_coeff=0.6, constraint_net_cn_lr=0.001, constraint_net_anneal_clr_by_factor=0.9, cost_gae_lambda=0.9, lambda_initial_value=0.1, lambda_lr=0.05, backward_iterations=5, backward_n_rollouts=50, constraint_net_batch_size=None, constraint_net_di_prior=[0.009, 0.001]
#  4) lr=0.00003, n_steps=2000, forward_steps=50000, n_iters=100, reward_gae_lambda=0.9, batch_size=128, epochs=20, clip_range=0.4, target_kl=0.01, constraint_net_layer1_size=20, constraint_net_layer2_size=None, constraint_net_regularizer_coeff=0.6, constraint_net_cn_lr=0.001, constraint_net_anneal_clr_by_factor=0.9, cost_gae_lambda=0.95, lambda_initial_value=5, lambda_lr=0.01, backward_iterations=5, backward_n_rollouts=50, constraint_net_batch_size=None, constraint_net_di_prior=[0.9, 0.1]
#  5) lr=0.00003, n_steps=2000, forward_steps=200000, n_iters=50, reward_gae_lambda=0.9, batch_size=128, epochs=20, clip_range=0.4, target_kl=0.02, constraint_net_layer1_size=40, constraint_net_layer2_size=40, constraint_net_regularizer_coeff=0.6, constraint_net_cn_lr=0.005, constraint_net_anneal_clr_by_factor=0.9, cost_gae_lambda=0.9, lambda_initial_value=0.1, lambda_lr=0.05, backward_iterations=5, backward_n_rollouts=50, constraint_net_batch_size=None, constraint_net_di_prior=[0.9, 0.1]
#  6) lr=0.00003, n_steps=2000, forward_steps=20000, n_iters=500, reward_gae_lambda=0.9, batch_size=128, epochs=20, clip_range=0.4, target_kl=0.02, constraint_net_layer1_size=20, constraint_net_layer2_size=None, constraint_net_regularizer_coeff=0.6, constraint_net_cn_lr=0.0001, constraint_net_anneal_clr_by_factor=0.9, cost_gae_lambda=0.9, lambda_initial_value=0.1, lambda_lr=0.01, backward_iterations=5, backward_n_rollouts=50, constraint_net_batch_size=None, constraint_net_di_prior=[0.09, 0.01]
#  7) lr=0.0001, n_steps=1000 (2000 used here), forward_steps=5000 (6000 used here), n_iters=500, reward_gae_lambda=0.95, batch_size=None, epochs=10, clip_range=0.2, target_kl=0.01, constraint_net_layer1_size=64, constraint_net_layer2_size=64, constraint_net_regularizer_coeff=0.5, constraint_net_cn_lr=0.005, constraint_net_anneal_clr_by_factor=0.9, cost_gae_lambda=0.9, lambda_initial_value=1.0, lambda_lr=0.01, backward_iterations=10, backward_n_rollouts=100, constraint_net_batch_size=500, constraint_net_di_prior=[9, 1]
#  8) lr=0.0001, n_steps=1000 (2000 used here), forward_steps=5000 (6000 used here), n_iters=150, reward_gae_lambda=0.95, batch_size=None, epochs=10, clip_range=0.2, target_kl=0.01, constraint_net_layer1_size=20, constraint_net_layer2_size=None, constraint_net_regularizer_coeff=0.5, constraint_net_cn_lr=0.005, constraint_net_anneal_clr_by_factor=0.5, cost_gae_lambda=0.95, lambda_initial_value=1.0, lambda_lr=0.01, backward_iterations=10, backward_n_rollouts=100, constraint_net_batch_size=500, constraint_net_di_prior=[0.9, 0.1]
#  9) same as (8) but with n_iters=500, constraint_net_cn_lr=0.0005, constraint_net_batch_size=1000
