game:
    # Options (we used):
    # - 'SafetyPointGoal1Debug-v0',
    # - 'SafetyCarButton1Debug-v0',
    # - 'SafetyCarPush2Debug-v0',
    # - 'SafetyPointCircle2Debug-v0'
    env_id: "SafetyPointGoal1Debug-v0"

Experiment:

  # Rendering
  render: True  # Should always be True
  render_mode: "human"
  freeze_motion: True

  # Debug mode specifications
  debug_action_smooth: 0.5  # Coefficient for smoothing the actions. Helpful for data collection to avoid extreme values of the action space.

  # Steps
  test_max_games: 40  # print avg reward in the interval
  test_max_timesteps_per_game: 1000  # max steps per trial. For "Circle" tasks, use 500.

  # Saving
  save_data_for_plots: False

  test_model: True # Dummy, just for triggering the right mode
  with_human: True # Human alone, or two humans
  test_seed: 2022  # None or int
  debug_: False
  test_window_size_moving_avg: 10
