# Example of a YAML configuration file for plotting multiple experiments.
# Each folder in `log_dirs` should contain folders with the results of different experiments,
# each of which should be named with an integer (e.g., "0", "1", "2", etc.).
# The legend list should have corresponding labels for each experiment.
log_dirs: [
  "~/training_results/icrl_results/icrl_reg-coef=0.0",
  "~/training_results/icrl_results/icrl_reg-coef=0.1",
  "~/training_results/icrl_results/icrl_reg-coef=0.2",
  "~/training_results/icrl_results/icrl_reg-coef=0.3",
  "~/training_results/icrl_results/icrl_reg-coef=0.4",
  "~/training_results/icrl_results/icrl_reg-coef=0.5",
  "~/training_results/icrl_results/icrl_reg-coef=0.6",
  "~/training_results/icrl_results/icrl_reg-coef=0.7",
  "~/training_results/icrl_results/icrl_reg-coef=0.8"
]

legends: [
  "reg-coef=0.0",
  "reg-coef=0.1",
  "reg-coef=0.2",
  "reg-coef=0.3",
  "reg-coef=0.4",
  "reg-coef=0.5",
  "reg-coef=0.6",
  "reg-coef=0.7",
  "reg-coef=0.8"
]

test_seed: "2024"
save_dir: "./icrl_multi_exp_results"