game:
    env_id: "SafetyPointGoal1Debug-v0"
    test_model: True # Dummy, just for triggering the right mode
    with_human: True # Human alone, or two humans
    save_data_for_plots: False

NO_ALGO:
  chkpt_dir: "human_alone_exp"

Experiment:
  render: True  # Should always be True
  render_mode: "human"
  freeze_motion: True
  debug_: False
  seed: None  # None or int
  test_max_games: 40  # print avg reward in the interval
  test_max_timesteps_per_game: 1000  # max steps per trial
  test_window_size_moving_avg: 10


