game:
  env_id: "SafetyPointGoal1-v0"
  with_human: False  # One or two humans if True
  use_image_obs: False

SAC:
  layer1_size: 32  # number of neurons in the first hidden layer
  layer2_size: 32  # number of neurons in the second hidden layer
  log_std_init: -3.0
  batch_size: 256
  gamma: 0.99
  tau: 0.005  # factor for polyak update of target networks
  alpha: 0.0003  # actor lr
  beta: 0.0003  # critic lr
  target_entropy: "auto"  # "auto", "auto_<float>", or float. In continuous case, there is no 'target_entropy_ratio', as opposed to 0.4 in discrete case.
  entropy_coefficient_lr: 0.0003  # In continuous case, the same lr with the networks is suggested, as opposed to 0.002 in discrete case.
  target_update_interval: 1  # how many gradient steps of online networks to perform before updating the target networks.
  use_sde: True  # Generalized State-Dependent Exploration
  sde_sample_freq: -1
  use_sde_at_warmup: False
  start_steps: 300  # 10000 # how many steps to collect transitions before learning starts
  num_steps: 4000  # 1000000 # Total environment steps. 'None' or integer. If 'None', specify 'n_episodes' or 'n_train_episodes'.
  buffer_memory_size: 1000000
  update_every_steps: 1  # Steps interval between two consecutive NN updates
  gradient_steps: 1  # How many steps to perform when updating
  clip_grad_norm: False
  max_grad_norm: 5

  ## Constraint optimization
  # General parameters
  w_constraint_optimization: True
  w_dual_grad_desc: False
  initial_lambda_constraint: 1.05
  lambda_constraint_lr: 0.0003
  # For KL Div approach
  w_kl_div: False
  w_entropy_in_constraint_policy_loss_term: False
  adjust_entropy: False
  w_mse: False
  mse_factor: 1.0
  nll_factor: 0.001
  pretrain: False
  only_pretrain: False
  pretrain_epochs: 10
  pretrain_mse_factor: 1.0
  pretrain_nll_factor: 0.001
  w_std_grads: False
  # For Q-values approach
  w_q_values: True
  w_max_min: True
  max_min_coef: 1.0
  w_lower_bound: False
  w_expectile_loss: False
  expectile_t: 0.9  # To penalize more the positive errors (i.e., rollout_q_value - dem_q_value_stat > 0 ==> rollout_q_value > dem_q_value_stat), choose values (0.5, 1.0]
  w_use_target_critic: False
  w_compute_analytically_min_dem_q_value: True
  dem_q_value_stat: 'min'  # The statistic to be used when 'w_compute_analytically_min_dem_q_value' is True. Options: 'min', 'mean', 'median', 'max', '25_quant', '75_quant'
  w_discriminator: True
  w_actions_in_discriminator: False
  discriminator_lr: 0.0003
  discriminator_batch_size: 256
  discriminator_gradient_steps: 1
  discriminator_layer1_size: 32  # number of neurons in the first hidden layer
  discriminator_layer2_size: 32 # number of neurons in the second hidden layer
  w_discriminator_icrl_regularization: False
  discriminator_icrl_regularization_coef: 0.5
  w_discriminator_dac_regularization: True
  discriminator_dac_regularization_coef: 10.0
  w_demonstrations_rl_term: True
  demonstrations_rl_term_coef: 1.0
  w_demonstrations_next_actions_in_demonstrations_rl_term: False
  w_entropy_in_demonstrations_rl_term: False
  w_compute_analytically_target_in_demonstrations_rl_term: True
  w_ood_rl_term: True
  ood_rl_term_coef: 1.0
  w_discriminator_rewards_in_ood_rl_term: True
  discriminator_reward_function_in_ood_rl_term: 'GAIL'  # Options: 'GAIL' (survival bonus), 'saturing_GANs_loss' (per step penalty), 'AIRL' (positive and negative components). From DAC: https://arxiv.org/pdf/1809.02925
  w_discriminator_discounted_rewards_in_ood_rl_term: False
  w_entropy_in_ood_rl_term: False
  w_gail_sac: False  # Pure GAIL without all the rest terms.
  discriminator_reward_function_in_gail_sac: 'GAIL'  # Options: 'GAIL' (survival bonus), 'saturing_GANs_loss' (per step penalty), 'AIRL' (positive and negative components). From DAC: https://arxiv.org/pdf/1809.02925

  # Demonstrations
  expert_dataset_path: '/home/georgepap/PycharmProjects/ModelFreeSafeIL/experiments/safety_gymnasium/demonstrations/human_alone_exp_human_data_simple_w_action_smooth=0.5/tmp/human_alone_exp_human_data_simple_w_action_smooth=0.5_1/demonstrations'
  load_demos_in_memory: True
  smooth_actions: False
  smooth_factor: 0.99

Experiment:

  # Normalization
  normalize_features: True
  normalize_rewards: False

  # Logging
  test_every_episodes: 2 # 5  # episodes interval between tests
  log_interval: 2 # 5  # print avg reward in the interval

  # Games/Steps
  max_timesteps_per_game: 1000  # max timesteps per episode in train mode
  test_max_timesteps_per_game: 1000  # max steps per episode in test mode
  test_max_games: 5  # 40  # print avg test reward in the interval

  # Saving
  save_model: True
  save_data_for_plots: False

  # Testing
  test_model: False # if True, no training
  load_checkpoint: False
  checkpoint_path: ""
  checkpoint_prefix: "last"  # Options: "best_reward", "lowest_constr", "last"

  render: False
  debug_: False
  test_window_size_moving_avg: 10
  seed: None  # None or int
  test_seed: 2024  # None or int
  device: "cpu"  # "cuda" or "cpu"
  torch_threads: 1


