output_path: "./unified_1_2_3_4_human_alone_exp_human_data_simple_w_action_smooth=0.5"

datasets:
  - "/home/georgepap/PycharmProjects/ModelFreeSafeIL/experiments/safety_gymnasium/demonstrations/SafetyPointGoal1-v0/unified_1_2_human_alone_exp_human_data_simple_w_action_smooth=0.5"
  - "/home/georgepap/PycharmProjects/ModelFreeSafeIL/experiments/safety_gymnasium/demonstrations/SafetyPointGoal1-v0/human_alone_exp_human_data_simple_w_action_smooth=0.5_3/test_results_seed=2021/tmp/demonstrations"
  - "/home/georgepap/PycharmProjects/ModelFreeSafeIL/experiments/safety_gymnasium/demonstrations/SafetyPointGoal1-v0/human_alone_exp_human_data_simple_w_action_smooth=0.5_4/test_results_seed=2020/tmp/demonstrations"