game:
    test_model: False # if TRUE, no training
    # The first item of the below lists refers to single agent path (if both X_agent and Y_agent are used, then checkpoint is shared).
    # The second item refers to X_Y_agent path.
    checkpoint_name: [
                      "",
                      "ppo_single_agent_exp_w_upper_constr_and_w_circle_constr_w_icrl_w_norm_reward_range_-1_0_w_n_iters=40_w_constraint_net_2_layers_w_lr_0.0003_w_back_iters=20_w_back_n_rollouts=100_1"
                     ]
    checkpoint_path: [
                      "",
                      "./../experiments/ppo_single_agent_exp_w_upper_constr_and_w_circle_constr_w_icrl_w_norm_reward_range_-1_0_w_n_iters=40_w_constraint_net_2_layers_w_lr_0.0003_w_back_iters=20_w_back_n_rollouts=100_1/train_results/tmp/"
                     ]
    load_checkpoint: False
    with_human: False # An agent plays with a human
    X_agent: False
    Y_agent: False
    X_Y_agent: True # If true, 'X_agent' and 'Y_agent' should be False
    X_Y_agent_pretrained: False # If true, 'X_Y_agent' should be False and 'load_checkpoint' should be True
    verbose: True
    save_data_for_plots: True
    save: True # save models and logs. If 'save_last' is false, the models will be saved based on the test reward.
    save_last: False # Save the last model instead of best. If it is True, 'save_constraints' and 'save_all' should be False. If 'save' is 'False', 'save_last' should also be 'False'.
    save_constraints: True # Save the model with the lowest number of constraints in test. If it is True, 'save_last' and 'save_all' should be False. If 'save' is 'False', 'save_constraints' should also be 'False'.
    save_all: False # Save and keep all models (i.e, after each epoch). Only applicable when 'SL_finetuning' is True. If it is True, 'save_last' and 'save_constraints' should be False. If 'save' is 'False', 'save_all' should also be 'False'.
    goal: "left_down" # "left_down" "left_up" "right_down"
    discrete: True # train_game_number board rotation velocity values
    scaling_x: 'auto' # Options: 'auto' or float like 0.01
    scaling_y: 'auto' # Options: 'auto' or float like 0.01

    # 13 iterations corresponds to 0.2 sec duration in a laptop with AMD ryzen 7 4000 series processor.
    # We need to explicitly define the number of environment updates during executing an action since
    # each machine performs different number of iterations for a predefined time duration. In this way,
    # we guarantee that the performance of agents will be consistent when running in different machines
    # as well as when running with render=True/False
    action_iterations: 5

PPO:
  layer1_size: 64  # number of variables in the first hidden layer
  layer2_size: 64 # number of variables in the second hidden layer
  lr: 0.0003 # learning rate of policy, value, and cost networks
  n_steps: 400 #2048 # number of steps per episode
  forward_steps : 2000 #200000 # number of steps per iteration (iterations = N of Algorithm 1 in ICRL)
  n_iters: 3 #3 #20 # number of iterations (N). n_iters*forward_steps gives the total number of steps
  reward_gamma: 0.99
  reward_gae_lambda: 0.95
  reward_vf_coef: 0.5
  max_grad_norm: 0.5
  batch_size: 10 #64
  epochs: 3 #20 # number of policy, value, and cost networks updates per episode
  clip_range: 0.2
  target_kl: 0.02
  ICRL_constraint_net_layer1_size: 40 # 20
  ICRL_constraint_net_layer2_size: 40 # None
  ICRL_constraint_net_regularizer_coeff: 0.5
  ICRL_constraint_net_cn_lr: 0.01
  ICRL_constraint_net_anneal_clr_by_factor: 0.9
  ICRL_constraint_net_target_kl_old_new: 10
  ICRL_constraint_net_target_kl_new_old: 2.5
  ICRL_cost_gamma: 0.99
  ICRL_cost_gae_lambda: 0.95
  ICRL_cost_vf_coef: 0.5
  ICRL_lambda_initial_value: 1.0
  ICRL_lambda_lr: 0.1
  ICRL_alpha_cost: 0.0
  ICRL_backward_iterations: 3 #10
  ICRL_backward_n_rollouts: 5 #50
  ICRL_constraint_net_batch_size: None
  ICRL: False
  lagrangian_lambda_initial_value: 1.05
  lagrangian_lambda_lr: 0.0003
  lagrangian: False
  normalize_features: True
  SL_finetuning: False # When 'SL_finetuning' is True, then 'ICRL' and 'lagrangian' should be false
  SL_finetuning_epochs: 5
  SL_finetuning_batch_size: 256
  SL_finetuning_lr: 0.0003

  # Sparse:   +100: goal, -50: time out, -1/step
  # Sparse_2: +10: goal, -1/step
  # Dense:    +10: goal, -[(distance from goal)/(regularize factor)]
  # Distance: +10: goal, -5: time out, -distance_from_goal/225: step (NOTE: maximum distance=450)
  reward_function: Distance

  expert_dataset_paths: [
    './../experiments/results_human_alone_sub1_single_traj_layout_3_sixth_row_bottom_1/tmp/human_alone_exp_test_1'
                        ]
  chkpt_dir: "ppo_single_agent_exp" #"ppo_two_agents_exp"

Experiment:
  log_interval: 4 # 40 # print avg reward in the interval
  max_timesteps_per_game: 200  # max timesteps per train_game_number
  test_max_games: 4 # 40 # print avg reward in the interval
  test_max_timesteps_per_game: 200 # max steps per trial
  render: False
  test_every_games: 4 # 40
  constraint_ball_only_at_the_right_side_wrt_hole: False
  constraint_ball_only_at_the_right_side_wrt_hole_x_coef: 1.6 # 2.
  constraint_ball_only_at_the_up_side_wrt_hole: True
  constraint_ball_only_at_the_up_side_wrt_hole_y_coef: 2.
  constraint_ball_not_in_circle: True
  constraint_ball_not_in_circle_circle_position: [ [ -90.0, -90.0 ] ] # [ [ -90.0, -90.0 ], [ -140.0, -40.0 ], [ -10.0, -100.0 ], [ 0.0, 100.0 ], [ 60.0, 40.0 ], [ 100.0, 100.0 ], [ 140.0, -20.0 ] ]
  constraint_ball_not_in_circle_circle_radius: [ 19.8398435 ] # [ 19.8398435, 19.8398435, 19.8398435, 19.8398435, 19.8398435, 19.8398435, 19.8398435 ]
  satisfied_constraint_value: 1.0
  not_satisfied_constraint_value: -10.0
  test_window_size_moving_avg: 10
  debug_: False
  test_seed: 2023

GUI:
  start_up_screen_display_duration: 5 # the time in sec the set-up screen is being displayed
  timeout_screen_display_duration: 3  # the time in sec the timeout screen is being displayed
  goal_screen_display_duration: 3 # the time in sec the goal screen is being displayed
